// Code generated by protoc-gen-go. DO NOT EDIT.
// source: message.proto

package pb

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Object_Kinect struct {
	Id                   uint32   `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	X                    uint32   `protobuf:"varint,2,opt,name=x,proto3" json:"x,omitempty"`
	Y                    uint32   `protobuf:"varint,3,opt,name=y,proto3" json:"y,omitempty"`
	Dist                 uint32   `protobuf:"varint,4,opt,name=dist,proto3" json:"dist,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Object_Kinect) Reset()         { *m = Object_Kinect{} }
func (m *Object_Kinect) String() string { return proto.CompactTextString(m) }
func (*Object_Kinect) ProtoMessage()    {}
func (*Object_Kinect) Descriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{0}
}

func (m *Object_Kinect) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Object_Kinect.Unmarshal(m, b)
}
func (m *Object_Kinect) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Object_Kinect.Marshal(b, m, deterministic)
}
func (m *Object_Kinect) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Object_Kinect.Merge(m, src)
}
func (m *Object_Kinect) XXX_Size() int {
	return xxx_messageInfo_Object_Kinect.Size(m)
}
func (m *Object_Kinect) XXX_DiscardUnknown() {
	xxx_messageInfo_Object_Kinect.DiscardUnknown(m)
}

var xxx_messageInfo_Object_Kinect proto.InternalMessageInfo

func (m *Object_Kinect) GetId() uint32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Object_Kinect) GetX() uint32 {
	if m != nil {
		return m.X
	}
	return 0
}

func (m *Object_Kinect) GetY() uint32 {
	if m != nil {
		return m.Y
	}
	return 0
}

func (m *Object_Kinect) GetDist() uint32 {
	if m != nil {
		return m.Dist
	}
	return 0
}

type Object_Omni struct {
	Id                   uint32   `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	X                    uint32   `protobuf:"varint,2,opt,name=x,proto3" json:"x,omitempty"`
	Y                    uint32   `protobuf:"varint,3,opt,name=y,proto3" json:"y,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Object_Omni) Reset()         { *m = Object_Omni{} }
func (m *Object_Omni) String() string { return proto.CompactTextString(m) }
func (*Object_Omni) ProtoMessage()    {}
func (*Object_Omni) Descriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{1}
}

func (m *Object_Omni) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Object_Omni.Unmarshal(m, b)
}
func (m *Object_Omni) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Object_Omni.Marshal(b, m, deterministic)
}
func (m *Object_Omni) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Object_Omni.Merge(m, src)
}
func (m *Object_Omni) XXX_Size() int {
	return xxx_messageInfo_Object_Omni.Size(m)
}
func (m *Object_Omni) XXX_DiscardUnknown() {
	xxx_messageInfo_Object_Omni.DiscardUnknown(m)
}

var xxx_messageInfo_Object_Omni proto.InternalMessageInfo

func (m *Object_Omni) GetId() uint32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Object_Omni) GetX() uint32 {
	if m != nil {
		return m.X
	}
	return 0
}

func (m *Object_Omni) GetY() uint32 {
	if m != nil {
		return m.Y
	}
	return 0
}

type Request struct {
	Check                bool     `protobuf:"varint,1,opt,name=check,proto3" json:"check,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Request) Reset()         { *m = Request{} }
func (m *Request) String() string { return proto.CompactTextString(m) }
func (*Request) ProtoMessage()    {}
func (*Request) Descriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{2}
}

func (m *Request) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Request.Unmarshal(m, b)
}
func (m *Request) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Request.Marshal(b, m, deterministic)
}
func (m *Request) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Request.Merge(m, src)
}
func (m *Request) XXX_Size() int {
	return xxx_messageInfo_Request.Size(m)
}
func (m *Request) XXX_DiscardUnknown() {
	xxx_messageInfo_Request.DiscardUnknown(m)
}

var xxx_messageInfo_Request proto.InternalMessageInfo

func (m *Request) GetCheck() bool {
	if m != nil {
		return m.Check
	}
	return false
}

type Response_Omni struct {
	Omni                 []byte         `protobuf:"bytes,1,opt,name=omni,proto3" json:"omni,omitempty"`
	Objects              []*Object_Omni `protobuf:"bytes,3,rep,name=objects,proto3" json:"objects,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *Response_Omni) Reset()         { *m = Response_Omni{} }
func (m *Response_Omni) String() string { return proto.CompactTextString(m) }
func (*Response_Omni) ProtoMessage()    {}
func (*Response_Omni) Descriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{3}
}

func (m *Response_Omni) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Response_Omni.Unmarshal(m, b)
}
func (m *Response_Omni) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Response_Omni.Marshal(b, m, deterministic)
}
func (m *Response_Omni) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Response_Omni.Merge(m, src)
}
func (m *Response_Omni) XXX_Size() int {
	return xxx_messageInfo_Response_Omni.Size(m)
}
func (m *Response_Omni) XXX_DiscardUnknown() {
	xxx_messageInfo_Response_Omni.DiscardUnknown(m)
}

var xxx_messageInfo_Response_Omni proto.InternalMessageInfo

func (m *Response_Omni) GetOmni() []byte {
	if m != nil {
		return m.Omni
	}
	return nil
}

func (m *Response_Omni) GetObjects() []*Object_Omni {
	if m != nil {
		return m.Objects
	}
	return nil
}

type Response_Kinect struct {
	Kinect               []byte           `protobuf:"bytes,1,opt,name=kinect,proto3" json:"kinect,omitempty"`
	KinectDepth          []byte           `protobuf:"bytes,2,opt,name=kinect_depth,json=kinectDepth,proto3" json:"kinect_depth,omitempty"`
	Objects              []*Object_Kinect `protobuf:"bytes,3,rep,name=objects,proto3" json:"objects,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *Response_Kinect) Reset()         { *m = Response_Kinect{} }
func (m *Response_Kinect) String() string { return proto.CompactTextString(m) }
func (*Response_Kinect) ProtoMessage()    {}
func (*Response_Kinect) Descriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{4}
}

func (m *Response_Kinect) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Response_Kinect.Unmarshal(m, b)
}
func (m *Response_Kinect) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Response_Kinect.Marshal(b, m, deterministic)
}
func (m *Response_Kinect) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Response_Kinect.Merge(m, src)
}
func (m *Response_Kinect) XXX_Size() int {
	return xxx_messageInfo_Response_Kinect.Size(m)
}
func (m *Response_Kinect) XXX_DiscardUnknown() {
	xxx_messageInfo_Response_Kinect.DiscardUnknown(m)
}

var xxx_messageInfo_Response_Kinect proto.InternalMessageInfo

func (m *Response_Kinect) GetKinect() []byte {
	if m != nil {
		return m.Kinect
	}
	return nil
}

func (m *Response_Kinect) GetKinectDepth() []byte {
	if m != nil {
		return m.KinectDepth
	}
	return nil
}

func (m *Response_Kinect) GetObjects() []*Object_Kinect {
	if m != nil {
		return m.Objects
	}
	return nil
}

func init() {
	proto.RegisterType((*Object_Kinect)(nil), "pb.Object_Kinect")
	proto.RegisterType((*Object_Omni)(nil), "pb.Object_Omni")
	proto.RegisterType((*Request)(nil), "pb.Request")
	proto.RegisterType((*Response_Omni)(nil), "pb.Response_Omni")
	proto.RegisterType((*Response_Kinect)(nil), "pb.Response_Kinect")
}

func init() {
	proto.RegisterFile("message.proto", fileDescriptor_33c57e4bae7b9afd)
}

var fileDescriptor_33c57e4bae7b9afd = []byte{
	// 333 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x92, 0xc1, 0x4f, 0xc2, 0x30,
	0x14, 0xc6, 0xd9, 0x40, 0x90, 0xb7, 0x4d, 0x42, 0x35, 0x66, 0xf1, 0x22, 0xee, 0x60, 0x30, 0x86,
	0x2d, 0xe2, 0x49, 0x4f, 0xc6, 0x78, 0x33, 0x91, 0x64, 0x9e, 0xf4, 0x42, 0xd6, 0xad, 0xd9, 0x2a,
	0xac, 0xad, 0xb4, 0x24, 0xec, 0xbf, 0x37, 0xb4, 0x95, 0x80, 0x37, 0x6f, 0xef, 0xf7, 0xf6, 0xbe,
	0xef, 0xbd, 0x6f, 0x29, 0x04, 0x35, 0x91, 0x32, 0x2b, 0x49, 0x2c, 0x56, 0x5c, 0x71, 0xe4, 0x0a,
	0x1c, 0xcd, 0x20, 0x98, 0xe1, 0x2f, 0x92, 0xab, 0xf9, 0x2b, 0x65, 0x24, 0x57, 0xe8, 0x04, 0x5c,
	0x5a, 0x84, 0xce, 0xc8, 0x19, 0x07, 0xa9, 0x4b, 0x0b, 0xe4, 0x83, 0xb3, 0x09, 0x5d, 0x8d, 0xce,
	0x66, 0x4b, 0x4d, 0xd8, 0x36, 0xd4, 0x20, 0x04, 0x9d, 0x82, 0x4a, 0x15, 0x76, 0x74, 0x43, 0xd7,
	0xd1, 0x03, 0x78, 0xd6, 0x70, 0x56, 0x33, 0xfa, 0x1f, 0xbb, 0xe8, 0x12, 0x7a, 0x29, 0xf9, 0x5e,
	0x13, 0xa9, 0xd0, 0x19, 0x1c, 0xe5, 0x15, 0xc9, 0x17, 0x5a, 0x79, 0x9c, 0x1a, 0x88, 0xde, 0x20,
	0x48, 0x89, 0x14, 0x9c, 0x49, 0x62, 0xdc, 0x11, 0x74, 0x78, 0xcd, 0xa8, 0x9e, 0xf2, 0x53, 0x5d,
	0xa3, 0x1b, 0xe8, 0x71, 0x7d, 0x80, 0x0c, 0xdb, 0xa3, 0xf6, 0xd8, 0x9b, 0x0e, 0x62, 0x81, 0xe3,
	0xbd, 0x9b, 0xd2, 0xdf, 0xef, 0x51, 0x03, 0x83, 0x9d, 0x9f, 0x8d, 0x7f, 0x0e, 0xdd, 0x85, 0xae,
	0xac, 0xa7, 0x25, 0x74, 0x05, 0xbe, 0xa9, 0xe6, 0x05, 0x11, 0xaa, 0xd2, 0x11, 0xfc, 0xd4, 0x33,
	0xbd, 0x97, 0x6d, 0x0b, 0xdd, 0xfe, 0x5d, 0x3c, 0xdc, 0x5b, 0x6c, 0xec, 0x77, 0xab, 0xa7, 0x8f,
	0xd0, 0xff, 0xe0, 0x4b, 0x6e, 0x62, 0x4c, 0xa0, 0xff, 0x4e, 0x58, 0x61, 0xc0, 0xdb, 0xaa, 0xec,
	0x7f, 0xb8, 0x18, 0x1a, 0xd8, 0xcb, 0x1c, 0xb5, 0xa6, 0x4f, 0xe0, 0x69, 0xad, 0x3d, 0xf9, 0x0e,
	0x3c, 0xad, 0xb6, 0x78, 0xa0, 0x3f, 0x3d, 0xd0, 0x9b, 0x89, 0xa8, 0xf5, 0x3c, 0xfe, 0xbc, 0x2e,
	0xa9, 0xaa, 0xd6, 0x38, 0xce, 0x79, 0x9d, 0x64, 0xab, 0x22, 0x63, 0xcb, 0x0c, 0xcb, 0x44, 0x34,
	0xaa, 0xe2, 0x6c, 0x52, 0xf2, 0xa4, 0x5c, 0x89, 0x3c, 0x11, 0x18, 0x77, 0xf5, 0x53, 0xb9, 0xff,
	0x09, 0x00, 0x00, 0xff, 0xff, 0x73, 0x1c, 0x78, 0x6c, 0x3b, 0x02, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// Yolo_OmniClient is the client API for Yolo_Omni service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type Yolo_OmniClient interface {
	Send_Omni(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response_Omni, error)
}

type yolo_OmniClient struct {
	cc grpc.ClientConnInterface
}

func NewYolo_OmniClient(cc grpc.ClientConnInterface) Yolo_OmniClient {
	return &yolo_OmniClient{cc}
}

func (c *yolo_OmniClient) Send_Omni(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response_Omni, error) {
	out := new(Response_Omni)
	err := c.cc.Invoke(ctx, "/pb.Yolo_Omni/Send_Omni", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Yolo_OmniServer is the server API for Yolo_Omni service.
type Yolo_OmniServer interface {
	Send_Omni(context.Context, *Request) (*Response_Omni, error)
}

// UnimplementedYolo_OmniServer can be embedded to have forward compatible implementations.
type UnimplementedYolo_OmniServer struct {
}

func (*UnimplementedYolo_OmniServer) Send_Omni(ctx context.Context, req *Request) (*Response_Omni, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Send_Omni not implemented")
}

func RegisterYolo_OmniServer(s *grpc.Server, srv Yolo_OmniServer) {
	s.RegisterService(&_Yolo_Omni_serviceDesc, srv)
}

func _Yolo_Omni_Send_Omni_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(Yolo_OmniServer).Send_Omni(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.Yolo_Omni/Send_Omni",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(Yolo_OmniServer).Send_Omni(ctx, req.(*Request))
	}
	return interceptor(ctx, in, info, handler)
}

var _Yolo_Omni_serviceDesc = grpc.ServiceDesc{
	ServiceName: "pb.Yolo_Omni",
	HandlerType: (*Yolo_OmniServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Send_Omni",
			Handler:    _Yolo_Omni_Send_Omni_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "message.proto",
}

// Yolo_KinectClient is the client API for Yolo_Kinect service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type Yolo_KinectClient interface {
	Send_Kinect(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response_Kinect, error)
}

type yolo_KinectClient struct {
	cc grpc.ClientConnInterface
}

func NewYolo_KinectClient(cc grpc.ClientConnInterface) Yolo_KinectClient {
	return &yolo_KinectClient{cc}
}

func (c *yolo_KinectClient) Send_Kinect(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response_Kinect, error) {
	out := new(Response_Kinect)
	err := c.cc.Invoke(ctx, "/pb.Yolo_Kinect/Send_Kinect", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Yolo_KinectServer is the server API for Yolo_Kinect service.
type Yolo_KinectServer interface {
	Send_Kinect(context.Context, *Request) (*Response_Kinect, error)
}

// UnimplementedYolo_KinectServer can be embedded to have forward compatible implementations.
type UnimplementedYolo_KinectServer struct {
}

func (*UnimplementedYolo_KinectServer) Send_Kinect(ctx context.Context, req *Request) (*Response_Kinect, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Send_Kinect not implemented")
}

func RegisterYolo_KinectServer(s *grpc.Server, srv Yolo_KinectServer) {
	s.RegisterService(&_Yolo_Kinect_serviceDesc, srv)
}

func _Yolo_Kinect_Send_Kinect_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(Yolo_KinectServer).Send_Kinect(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.Yolo_Kinect/Send_Kinect",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(Yolo_KinectServer).Send_Kinect(ctx, req.(*Request))
	}
	return interceptor(ctx, in, info, handler)
}

var _Yolo_Kinect_serviceDesc = grpc.ServiceDesc{
	ServiceName: "pb.Yolo_Kinect",
	HandlerType: (*Yolo_KinectServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Send_Kinect",
			Handler:    _Yolo_Kinect_Send_Kinect_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "message.proto",
}
