# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: protoFiles/CDB2Ctrl.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x19protoFiles/CDB2Ctrl.proto\"\x95\x05\n\x08\x43\x44\x42\x32\x43trl\x12\x1a\n\x12intersection_point\x18\x01 \x01(\x02\x12\x0f\n\x07\x63ompass\x18\x02 \x01(\x02\x12\x11\n\tstateBall\x18\x03 \x01(\x05\x12\x10\n\x08kick_cap\x18\x04 \x01(\x02\x12*\n\x0b\x62\x61seStation\x18\x05 \x01(\x0b\x32\x15.CDB2Ctrl.BaseStation\x12!\n\x05robot\x18\x06 \x01(\x0b\x32\x12.CDB2Ctrl.Position\x12 \n\x04\x62\x61ll\x18\x07 \x01(\x0b\x32\x12.CDB2Ctrl.Position\x12%\n\tgoalPosts\x18\x08 \x03(\x0b\x32\x12.CDB2Ctrl.Position\x12\"\n\x06robots\x18\t \x03(\x0b\x32\x12.CDB2Ctrl.Position\x12#\n\x07\x66riends\x18\n \x03(\x0b\x32\x12.CDB2Ctrl.Position\x12%\n\topponents\x18\x0b \x03(\x0b\x32\x12.CDB2Ctrl.Position\x12\"\n\x06humans\x18\x0c \x03(\x0b\x32\x12.CDB2Ctrl.Position\x1a\x8e\x01\n\x08Position\x12\t\n\x01x\x18\x01 \x01(\x02\x12\t\n\x01y\x18\x02 \x01(\x02\x12\x0b\n\x03\x61ng\x18\x03 \x01(\x02\x12\x0c\n\x04\x64ist\x18\x04 \x01(\x02\x12\x0c\n\x04\x63onf\x18\x05 \x01(\x02\x12\x0e\n\x06x_pred\x18\x06 \x01(\x02\x12\x0e\n\x06y_pred\x18\x07 \x01(\x02\x12\x10\n\x08\x61ng_pred\x18\x08 \x01(\x02\x12\x11\n\tdist_pred\x18\t \x01(\x02\x1az\n\x0b\x42\x61seStation\x12\t\n\x01s\x18\x01 \x01(\x05\x12\x0c\n\x04\x61rg0\x18\x02 \x01(\x02\x12\x0c\n\x04\x61rg1\x18\x03 \x01(\x02\x12\x0c\n\x04\x61rg2\x18\x04 \x01(\x02\x12\x0c\n\x04\x61rg3\x18\x05 \x01(\x02\x12\x0c\n\x04\x61rg4\x18\x06 \x01(\x02\x12\x0c\n\x04\x61rg5\x18\x07 \x01(\x02\x12\x0c\n\x04\x61rg6\x18\x08 \x01(\x02\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'protoFiles.CDB2Ctrl_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_CDB2CTRL']._serialized_start=30
  _globals['_CDB2CTRL']._serialized_end=691
  _globals['_CDB2CTRL_POSITION']._serialized_start=425
  _globals['_CDB2CTRL_POSITION']._serialized_end=567
  _globals['_CDB2CTRL_BASESTATION']._serialized_start=569
  _globals['_CDB2CTRL_BASESTATION']._serialized_end=691
# @@protoc_insertion_point(module_scope)
