# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: protoFiles/Ctrl2CDB.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x19protoFiles/Ctrl2CDB.proto\"\xf7\x01\n\x08\x43trl2CDB\x12\n\n\x02ID\x18\x01 \x01(\x05\x12\x10\n\x08loopTime\x18\x02 \x01(\x05\x12\x16\n\x0eloopPrecentage\x18\x03 \x01(\x05\x12\x12\n\nlinear_vel\x18\x04 \x01(\x05\x12\x13\n\x0b\x61ngular_vel\x18\x05 \x01(\x05\x12\x11\n\tdirection\x18\x06 \x01(\x05\x12\x11\n\tX_desired\x18\x07 \x01(\x02\x12\x11\n\tY_desired\x18\x08 \x01(\x02\x12\x10\n\x08pwm_kick\x18\t \x01(\x05\x12\x11\n\tdribblers\x18\n \x01(\x05\x12\x0c\n\x04\x61rms\x18\x0b \x01(\x05\x12\x11\n\tA_desired\x18\x0c \x01(\x02\x12\r\n\x05skill\x18\r \x01(\x0c\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'protoFiles.Ctrl2CDB_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_CTRL2CDB']._serialized_start=30
  _globals['_CTRL2CDB']._serialized_end=277
# @@protoc_insertion_point(module_scope)
